name: CI-CD Mochila GPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar PlatformIO
        run: pip install platformio
      - name: Compilar firmware ESP32
        run: pio run

  test-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
      - name: Obtener dependencias
        run: flutter pub get
      - name: Ejecutar pruebas
        run: flutter test

  deploy:
    needs: [build-firmware, test-flutter]
    runs-on: ubuntu-latest
    steps:
      - name: Build APK Release
        run: flutter build apk --release
